Interleaved Multi-head Attention Operators
awslabs/sockeye pull request #884
Opened 2020-09-23 00:39 UTC by blchu

Replaced batched dot product in multi-head attention with interleaved_matmul attention operators to improve performance. Also changes the batch-major data to time-major format while in the model to comply with the new operator requirements.

Replacing https://github.com/awslabs/sockeye/pull/814 due to issues with diffs against the master branch.

#### Pull Request Checklist ##
- [ ] Changes are complete (if posting work-in-progress code, prefix your pull request title with '[WIP]'
until you can check this box.
- [ ] Unit tests pass (`pytest`)
- [ ] Were system tests modified? If so did you run these at least 5 times to account for the variation across runs?
- [ ] System tests pass (`pytest test/system`)
- [ ] Passed code style checking (`./style-check.sh`)
- [ ] You have considered writing a test
- [ ] Updated major/minor version in `sockeye/__init__.py`. Major version bump if this is a backwards incompatible change.
- [ ] Updated CHANGELOG.md

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-24 01:34 UTC, blchu commented
@tdomhan My changes are not backward compatible with previous versions of Sockeye, and so requires a major version update. How should I modify the backwards compatibility test that you introduced to account for this?

2020-09-24 11:29 UTC, tdomhan commented
That's a good point! I guess there's no way to make things backwards compatible. 

So what we should do is create a `model_2.2.x` using the sequence copy data/the command from here:
https://github.com/awslabs/sockeye/blob/master/test/data/model_2.1.x/README.md
and delete model_2.1.x.

Does that work for you?

2020-09-24 17:25 UTC, blchu commented
Sure, I'll go ahead and do that.

2020-09-28 12:40 UTC, barbaradarques requested changes

2020-09-28 12:40 UTC, barbaradarques commented on sockeye/layers.py
> +                key_values: mx.sym.Symbol,
Update docstring accordingly.

2020-09-28 12:40 UTC, barbaradarques commented on sockeye/layers.py
> +                       projected_memory_kv: Optional[mx.sym.Symbol] = None) -> mx.sym.Symbol:  # mypy: ignore
Update docstring.

2020-09-28 12:40 UTC, barbaradarques commented on sockeye/layers.py
> +    def hybrid_forward(self, F, queries, key_values, heads, lengths=None, bias=None):
Update calls/docstrings at `ProjectedDotAttention` (https://github.com/awslabs/sockeye/pull/884/files#diff-74c804465509cbab074609c50c13a8f7L710) and `PlainDotAttention` (https://github.com/awslabs/sockeye/pull/884/files#diff-74c804465509cbab074609c50c13a8f7L642).

2020-09-28 12:40 UTC, barbaradarques commented on sockeye/transformer.py
> -        target_autoregr, *new_autoregr_states = self.autoregr_layer(self.pre_autoregr_layer(target, None),
As mentioned above, we should maintain the unpacking in order to keep supporting autoregressive layers with more than one state tensor.

2020-09-30 21:22 UTC, blchu commented
@tdomhan @barbaradarques @mjdenkowski @fhieber Are there any potential issues left with this PR, or would it be ready to be merged in now?

2020-10-01 08:34 UTC, barbaradarques commented
Hi @blchu, I'm still finding a discrepancy in perplexity, both with and without SSRUs.

2020-10-01 08:51 UTC, barbaradarques commented
But thanks for iterating! All the things I pointed out in the previous review were covered.

2020-10-01 11:37 UTC, barbaradarques commented
Updating on the output of my tests, I also got an output of only <unk>'s in the SSRU version.

2020-10-02 08:53 UTC, blchu commented
@barbaradarques could you tell me what you ran to get those results so I can try to replicate it on my side? From looking at system test outputs I'm not noticing any significant discrepancy in perplexity, and training both a transformer model and SSRU model on a WMT dataset (and comparing to master) gets expected results for training perplexity, BLEU, and translation output.

2020-10-02 08:57 UTC, barbaradarques commented
@blchu Interesting. I will double check my own tests then, before we deep diver into this.

2020-10-02 09:02 UTC, barbaradarques commented
Also, in order to remove the effect of the Xavier initializer, I replaced it with [mxnet.initializer.One](https://mxnet.apache.org/versions/1.6/api/python/docs/api/initializer/index.html#mxnet.initializer.One).

2020-10-02 10:18 UTC, fhieber commented
I tried reproducing the differences locally on my laptop, using a common toy sequence copy task (validation data == training data). The command is:
```
python3 -m sockeye.train --use-cpu -s data/dev.source -t data/dev.target -vs data/dev.source -vt data/dev.target --num-embed 32 --batch-size 10 --batch-type sentence -o blchu_transformer --num-layers 2:2 --overwrite-output --transformer-model-size 32 --weight-tying-type src_trg_softmax --max-updates 8000 --decode-and-evaluate 10 --checkpoint-interval 2000 \
	--decoder DECODER -o MODEL
```
where DECODER is `{transformer, ssru_transformer}` and MODEL is an output folder.

The training perplexity after the first 50 batches:
```
blchu_ssru/log: Epoch[0] Batch [50]	perplexity=19.079991
blchu_transformer/log: Epoch[0] Batch [50]	perplexity=18.648705
master_ssru/log: Epoch[0] Batch [50] perplexity=18.851622
master_transformer/log: Epoch[0] Batch [50]	perplexity=17.698212
```

After 8000 updates:
```
blchu_ssru/log: Epoch[79] Batch [8000] perplexity=2.035750
blchu_transformer/log: Epoch[79] Batch [8000]perplexity=2.099237
master_ssru/log: Epoch[79] Batch [8000]	perplexity=2.030470
master_transformer/log: Epoch[79] Batch [8000]perplexity=2.107919
```

Last checkpoint (4):
```
blchu_ssru/log: Checkpoint [4]	Validation-perplexity=1.754443	Validation-bleu=1.000000	Validation-chrf=1.000000	Validation-rouge1=0.930180	Validation-rouge2=0.937282	Validation-rougel=0.943623	Validation-length-ratio-mse=1.000000	Validation-avg-sec-per-sent=0.016261	Validation-decode-walltime=0.162612
blchu_transformer/log: Checkpoint [4]	Validation-perplexity=1.758212	Validation-bleu=1.000000	Validation-chrf=1.000000	Validation-rouge1=0.930180	Validation-rouge2=0.937282	Validation-rougel=0.943623	Validation-length-ratio-mse=1.000000	Validation-avg-sec-per-sent=0.022654	Validation-decode-walltime=0.226536
master_ssru/log: Checkpoint [4]	Validation-perplexity=1.754248	Validation-bleu=1.000000	Validation-chrf=1.000000	Validation-rouge1=0.930180	Validation-rouge2=0.937282	Validation-rougel=0.943623	Validation-length-ratio-mse=1.000000	Validation-avg-sec-per-sent=0.016961	Validation-decode-walltime=0.169605
master_transformer/log: Checkpoint [4]	Validation-perplexity=1.756007	Validation-bleu=1.000000	Validation-chrf=1.000000	Validation-rouge1=0.930180	Validation-rouge2=0.937282	Validation-rougel=0.943623	Validation-length-ratio-mse=1.000000	Validation-avg-sec-per-sent=0.032418	Validation-decode-walltime=0.324185
```


This looks fine to me, @barbaradarques

2020-10-02 10:23 UTC, barbaradarques commented
I probably tampered with it too much. So, other than that, everything else looks good to me!

2020-10-02 10:28 UTC, barbaradarques approved these changes

2020-10-02 10:30 UTC, fhieber approved these changes
We've gone over this a lot, thanks for iterating and bringing it over the finish line. LGTM

2020-10-02 13:34 UTC, tdomhan approved these changes

2020-10-02 14:18 UTC, merged